---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: longhorn-frontend-cert
  namespace: longhorn-system
spec:
  commonName: longhorn-dashboard.danmanners.io
  secretName: longhorn-frontend-cert
  dnsNames:
    - longhorn-dashboard.danmanners.io
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: allow-rfc1918
  namespace: longhorn-system
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
---
# BE INCREDIBLY CAREFUL WITH THIS. Don't expose it to the open internet, as this dashboard
# IS FULL ADMIN ACCESS ONLY ! ! ! !
# Don't say I didn't warn you.
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn-dashboard.danmanners.io`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: allow-rfc1918
          namespace: longhorn-system
  tls:
    secretName: longhorn-frontend-cert
