apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.1.0
    chart: longhorn
    helm:
      valueFiles:
        - values.yaml
      values: |
        image:
          csi:
            attacher:
              repository: longhornio/csi-attacher
              tag: v2.2.1-lh1
            nodeDriverRegistrar:
              repository: longhornio/csi-node-driver-registrar
              tag: v1.2.0-lh1
            provisioner:
              repository: longhornio/csi-provisioner
              tag: v1.6.0-lh1
            resizer:
              repository: longhornio/csi-resizer
              tag: v0.5.1-lh1
            snapshotter:
              repository: longhornio/csi-snapshotter
              tag: v2.1.1-lh1
          longhorn:
            engine:
              repository: longhornio/longhorn-engine
              tag: v1.1.0
            instanceManager:
              repository: longhornio/longhorn-instance-manager
              tag: v1_20201216
            manager:
              repository: longhornio/longhorn-manager
              tag: v1.1.0
            shareManager:
              repository: longhornio/longhorn-share-manager
              tag: v1_20201204
            ui:
              repository: longhornio/longhorn-ui
              tag: v1.1.0
          pullPolicy: IfNotPresent
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
        service:
          manager:
            type: ClusterIP
          ui:
            type: ClusterIP
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true