kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-xfs
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
provisioner: driver.longhorn.io
parameters:
  baseImage: ''
  fromBackup: ''
  fsType: xfs
  numberOfReplicas: '2'
  staleReplicaTimeout: '30'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
