apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    namespace: bitnami
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: "14.2.3"
    chart: elasticsearch
    helm:
      valueFiles:
        - values.yaml
      values: |
        global:
          imagePullSecrets:
            - regcred
          storageClass: longhorn-xfs
        clusterDomain: kube.danmanners.io
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true