apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
spec:
  destination:
    namespace: bitnami
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: "3.6.2"
    chart: fluentd
    helm:
      valueFiles:
        - values.yaml
      values: |
        clusterDomain: kube.danmanners.io
        global:
          imagePullSecrets:
            - regcred
          storageClass: longhorn-xfs
        fowarder:
          service:
            type: LoadBalancer
        aggregator:
          configMap: elasticsearch-output
          extraEnv:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch-elasticsearch-data.bitnami.svc.kube.danmanners.io"
            - name: ELASTICSEARCH_PORT
              value: "9200"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true