---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-cert
  namespace: argocd
spec:
  commonName: argocd.danmanners.io
  secretName: argo-cert
  dnsNames:
    - argocd.danmanners.io
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.danmanners.io`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: argo-cert