---
## ArgoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'argocd-projects'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: ArgoCD
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
## Nexus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nexus-oss'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: Nexus-OSS
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
## Jenkins
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'jenkins'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: Jenkins
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
## SonarQube
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'sonarqube'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: Sonarqube
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: sonarqube
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
## GitLab-EE
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'gitlab-deployment'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: Gitlab
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: gitlab
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
## Whoami
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'whoami-kustomization'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: validation-apps
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
## Bitnami Tools
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'bitnami-global'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: Bitnami
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: bitnami
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
## OpenFaaS
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'openfaas-project'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: OpenFaaS
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: openfaas
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
