---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'sonarqube'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: Sonarqube
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: sonarqube
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'gitlab-deployment'
  namespace: argocd
spec:
    project: default
    source:
        repoURL: 'git@github.com:danmanners/RKE-Learning-2.git'
        path: Gitlab
        targetRevision: HEAD
    destination:
        server: 'https://kubernetes.default.svc'
        namespace: gitlab
    syncPolicy:
        automated:
            prune: true
        syncOptions:
            - CreateNamespace=true
