apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./base/
- ./traefik_ingress/ # If using Traefik as your ingress, uncomment this line. Don't uncomment both!
# - metallb_ingress/ # If using MetalLB as your ingress, uncomment this line. Don't uncomment both!

patchesStrategicMerge:
- user-edits/unifi-overrides.yaml
- user-edits/mongo-overrides.yaml
# - user-edits/ingress.yaml # 
