---
## ArgoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "unifi-controller"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:danmanners/RKE-Learning-2.git"
    # repoURL should be set to your project, unless you wsssssant to launch this one specifically, which you probably don't.
    path: Unifi-Controller
    targetRevision: unifi-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: unifi-controller
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true