apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
    metallb.universe.tf/address-pool: update_in_user_edits
  labels:
    app: unifi-controller
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: unifi-controller
  loadBalancerIP: load_balancer_ip_goes_here
  ports:
    - name: "l2-discoverable"
      protocol: UDP
      targetPort: 1900
      port: 1900
    - name: "stun"
      protocol: UDP
      targetPort: 3478
      port: 3478
    - name: "ap-discovery"
      protocol: UDP
      targetPort: 10001
      port: 10001
