---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
  namespace: cert-manager
data:
  # insert your DO access token here
  access-token: "ReplaceThisWithBase64DigitalOceanApiKey"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-prod
spec:
  acme:
    email: daniel.a.manners@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-prod-account-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
      selector:
        dnsZones:
        - 'danmanners.io'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: whoami-cert
spec:
  commonName: whoami.danmanners.io
  secretName: whoami-cert
  dnsNames:
    - whoami.danmanners.io
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
